package com.example.a4kvideodownloaderplayer.ads.banner_ads

enum class BannerAdType {
    DEFAULT_BANNER,
    DEFAULT_BANNER_NEW_INSTANCE,
    RECTANGLE_BANNER,
    RECTANGLE_BANNER_NEW_INSTANCE,
    COLLAPSIBLE_BANNER,
    COLLAPSIBLE_BANNER_NEW_INSTANCE,
    INLINE_ADAPTIVE_BANNER,
    INLINE_ADAPTIVE_BANNER_NEW_INSTANCE
}